### ISSUE TITLE
Multiplayer Groups Time Issue - Latest iOS version

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#10] opened 2017-04-22 18:42 UTC
It always shows 00:00:00.
Pics uploaded.
![18058026_804346826385756_1038112416042123064_n](https://cloud.githubusercontent.com/assets/27891393/25307139/357e8fc4-279c-11e7-95c6-94250a9d839b.jpg)

![18033856_804346903052415_53616723854530606_n](https://cloud.githubusercontent.com/assets/27891393/25307171/988035be-279c-11e7-96e0-4f67bd7d071d.jpg)

**Comment by guthyerrz** [comment] 2017-05-15 20:26
We could not reproduce this bug, we talked with the player who is having this problem and he can play the game normally even with this bug.
I'm closing this bug for now. If more information about this bug come out we will reopen it

**Closed as completed by guthyerrz** 2017-05-15 20:26 UTC
Labels: groups, ios
